### ISSUE TITLE
the regex used to remove all text that is not included in the <body> element causes node to get stuck

### ISSUE THREAD

**Issue by regevbr** [EDMdesigner/textversionjs#13]
In the case the html is very long and doesnt include a body element (yes it can happen to me) the regex used causes the node js process to get stuck on 100% cpu for a long time.
Instead we can use a better approach - look for the index of the body element (without using the * matcher) and then use substring to cut out the desired text.
E.g. 
```javascript
	// remove everything before and after <body> tags including the tag itself
	const bodyEndMatch = tmp.match(/<\/body>/i);
	if (bodyEndMatch) {
		tmp = tmp.substring(0, bodyEndMatch.index);
	}
	const bodyStartMatch = tmp.match(/<body[^>]*>/i);
	if (bodyStartMatch) {
		tmp = tmp.substring(bodyStartMatch.index + bodyStartMatch[0].length, tmp.length);
	}
```

**Comment by stubendek** [comment]
Hi, regevbr, thank you for the issue and the pull request, we will look at it soon.

**Comment by stubendek** [comment]
Hi, @regevbr , we updated the package. Thanks for your PR. Please confirm the updated functionality.

**Comment by regevbr** [comment]
@stubendek I already used that fix in my fork and it works well for 10 days now
