### ISSUE TITLE
Tables?

### ISSUE THREAD

**Issue by tomgallagher** [EDMdesigner/textversionjs#2]
Hey

Nice utility this, saved me some time, thanks!

Have you ever thought about whether you could generate a text version of tables? Like, using the same sort of methodology you use for headings and lists?

cheers

Tom

**Comment by stubendek** [comment]
Hi!

Thank you for your comment! The primary purpose of this tool is to get plain text version of html emails, and most of these htmls contain tons of tables. However it is a good idea to offer table conversion as an option. Do you have a suggestion how the output should look like? Any ideas are more than welcome!

Attila

**Comment by tomgallagher** [comment]
Hi

I had a look through your code and noticed that you were already treating
<td> elements in a special way. So at the moment the table data comes out
clean but each element is on a new line. The original design of the table is
lost as headings and columns do not match up.

To make a table work in conversion to plain text, it's all going to be about
counting characters and spaces.  The main challenge would be making the
table headers line up with the table data underneath.  I'd just delete
footers as they often come in the 'wrong' order in an HTML table.

In the html table you do a count of the <th> elements to give you column
numbers. You allocate 20 spaces to each <th> element in the header, count
the characters in the <th> text itself then add the remainder of spaces. Do
the same kind of thing on each line of <td> and you should end up with
something that is spaced like an html table. Adding lining etc is not
something I know anything about but <th> elements could be underlined.

You will struggle to put together a routine that works for irregular tables,
i.e. where one row stretches across many columns, but as long as that
scenario doesn't break it, I think that's fine.

Just a few thoughts. Thanks again for the useful routine.

Tom

**Comment by stubendek** [comment]
Hi!

Thank you for your ideas!

What we can image is to plainify only non-nested tables, nested ones would cause unexpected behavior and the readability would be lost also.

Since we are working on e-mail htmls, where usually tables are nested in huge deepnesses, we did not put this issue on our rodemap. However, in the future if an update will be needed we will implement this feature and let you know about that.

Attila
