### ISSUE TITLE
Paste from Word or Google Docs: some tags are not removed

### ISSUE THREAD

**Issue by ymatrokhin** [EDMdesigner/textversionjs#3]
Hi!

I've faced a little problem with textversionjs while pasting text\html from word or google docs.
Some tags are not unsignificant tags are not replaced from text.

1. Paste from google docs
html: 
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1fcf0a00-244c-6cac-3347-0fc5c1fcd024"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:30.666666666666664px;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">line 1</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:30.666666666666664px;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">line 2</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:30.666666666666664px;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">line 3</span></p></b><br class="Apple-interchange-newline">

text: 
**<meta charset="utf-8">**
line 1
line 2
line 3

2. paste from Word
html:
     <p class=MsoNormal><span lang=EN-US style='font-size:10.5pt;line-height:107%;  font-family:"Arial",sans-serif;color:#333333;mso-ansi-language:EN-US'>Line 1<o:p></o:p></span></p>    <p class=MsoNormal><span lang=EN-US style='font-size:10.5pt;line-height:107%;  font-family:"Arial",sans-serif;color:#333333;mso-ansi-language:EN-US'>Line 2</span><span  lang=EN-US style='mso-ansi-language:EN-US'><o:p></o:p></span></p>    <p class=MsoNormal><span lang=EN-US style='font-size:10.5pt;line-height:107%;  font-family:"Arial",sans-serif;color:#333333;mso-ansi-language:EN-US'>Line 3</span><span  lang=EN-US style='mso-ansi-language:EN-US'><o:p></o:p></span></p>    

text: 
Line 1**<o:p></o:p>**
Line 2**<o:p></o:p>**
Line 3**<o:p></o:p>**

Probably, the source of this error in this line of code:
tmp = tmp.replace(/<((?!h[1-6]( [^>]*)*>)(?!img( [^>]*)*>)(?!a( [^>]*)*>)(?!ul( [^>]*)*>)(?!ol( [^>]*)*>)(?!li( [^>]*)*>)(?!p( [^>]*)*>)(?!div( [^>]*)*>)(?!td( [^>]*)*>)(?!br( [^>]*)*>)[^>])*>/gi, "");

Tags, that ends up with "a ", "p " are not replaced. Even if any attribute contains "a ", "p ", "br " - this tags are not removed: 
<span **test="a "** lang=EN-US style='font-size:10.5pt;line-height:107%; font-family:"Arial",sans-serif;color:#333333;mso-ansi-language:EN-US'>

I've tried the regex below, it seems to work fine:
tmp = tmp.replace(/<(\/)?(?!h[1-6]( [^>\/]*)*>)(?!img( [^>\/]*)*>)(?!a( [^>\/]*)*>)(?!ul( [^\/>]*)*>)(?!ol( [^>\/]*)*>)(?!li( [^>\/]*)*>)(?!p( [^>\/]*)*>)(?!div( [^>\/]*)*>)(?!td( [^>\/]*)*>)(?!br( [^>\/]*)*>)[^>\/]*>/gi, "");
It should check exectly the full name of tag.

Will you please check my suggestion and fix this defect?

Regards, Yuri

**Comment by stubendek** [comment]
Hi, Yuri!

Thank you for the issue and especially for your suggestion how to fix it. We will check it in a while and update the code!

Regards,
Attila

**Comment by stubendek** [comment]
Hi!

We've pushed an update based on your suggestion, however without putting slash into negative lookaheads and into the final filler - in order not to catch for example style declarations with slashes (`url: .../..`.) and single tags ending with slash (`<img ... />`).

Please let us know if the update worked for you also.

Thank you again for the issue!

Attila

**Comment by ymatrokhin** [comment]
Thanks a lot, now it works for me!

**Comment by stubendek** [comment]
Great!
