### ISSUE TITLE
Non-breaking space not respected

### ISSUE THREAD

**Issue by ianjepperson** [EDMdesigner/textversionjs#4]
According to spec, `&nbsp;` should always be represented as a space and not collapsed.  However it is being collapsed with other spaces and non-breaking spaces.
```
> textVersion('aaa&nbsp;&nbsp;&nbsp;bbb');
'aaa bbb\n'
```
Expected 
```
'aaa   bbb'
```
 (3 spaces)

Reference:
https://en.wikipedia.org/wiki/Non-breaking_space#Non-collapsing_behavior

Thanks!

**Comment by ianjepperson** [comment]
Looks like this is being done on this line: https://github.com/EDMdesigner/textversionjs/blob/master/src/textversion.js#L153

**Comment by ianjepperson** [comment]
(oops, wrong button)

**Comment by stubendek** [comment]
H!

Thank you for the issue. We were thinking about your idea. We would suggest to add an extra option about the non-breaking spaces, to have the possibility to collapse or keep them. Soon we will update the code and let you know.

Attila

**Comment by stubendek** [comment]
Hi, we added the requested functionality. nbsps are handled as a whitespace by default, but with the keepNbsps option set true, you can keep those characters (included in the readme). The updated version is now available. Please confirm that the update meets your requests.

**Comment by stubendek** [comment]
Hi, @ianjepperson , we added the requested functionality, please, confirm that it fullfills your needs. Best, A
