### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by sharpensteel** [EDMdesigner/textversionjs#7]
Hi, there is an error if `<ol>` have attribute `start` with value greater then one symbol:

```
var createTextVersion = require('textversionjs');
createTextVersion('<ol start="10">test</ol>');
```
```
TypeError: Cannot read property '1' of null
    at textversion.js:86
```

i tried to create merge request: https://github.com/EDMdesigner/textversionjs/pull/6

**Comment by stubendek** [comment]
Dear sharpensteel,
thank you for the issue and the bugfix as well!
Attila
